# Generated by Django 4.1.3 on 2023-08-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USMAApp', '0010_hob_experts'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities',
            name='UniversityLink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
