# Generated by Django 4.1.3 on 2023-08-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USMAApp', '0011_universities_universitylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='allprojects',
            name='ProjectLink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='ModuleLink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='universitycourses',
            name='CourseLink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
