# Generated by Django 4.1.3 on 2023-08-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USMAApp', '0012_allprojects_projectlink_modules_modulelink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UdsmUniversityCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(blank=True, max_length=100, null=True)),
                ('CourseImage', models.ImageField(blank=True, null=True, upload_to='media/UniversityImage/')),
                ('CourseDepartment', models.CharField(blank=True, max_length=100, null=True)),
                ('CourseCapacity', models.IntegerField(blank=True, null=True)),
                ('CourseLink', models.CharField(blank=True, default='USMA/', max_length=500, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('university', models.ManyToManyField(max_length=200, to='USMAApp.universities')),
            ],
            options={
                'verbose_name_plural': 'UdsmUniversityCourses',
            },
        ),
        migrations.CreateModel(
            name='UdomUniversityCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(blank=True, max_length=100, null=True)),
                ('CourseImage', models.ImageField(blank=True, null=True, upload_to='media/UniversityImage/')),
                ('CourseDepartment', models.CharField(blank=True, max_length=100, null=True)),
                ('CourseCapacity', models.IntegerField(blank=True, null=True)),
                ('CourseLink', models.CharField(blank=True, default='USMA/', max_length=500, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('university', models.ManyToManyField(max_length=200, to='USMAApp.universities')),
            ],
            options={
                'verbose_name_plural': 'UdomUniversityCourses',
            },
        ),
        migrations.CreateModel(
            name='MustUniversityCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(blank=True, max_length=100, null=True)),
                ('CourseImage', models.ImageField(blank=True, null=True, upload_to='media/UniversityImage/')),
                ('CourseDepartment', models.CharField(blank=True, max_length=100, null=True)),
                ('CourseCapacity', models.IntegerField(blank=True, null=True)),
                ('CourseLink', models.CharField(blank=True, default='USMA/', max_length=500, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('university', models.ManyToManyField(max_length=200, to='USMAApp.universities')),
            ],
            options={
                'verbose_name_plural': 'MustUniversityCourses',
            },
        ),
        migrations.CreateModel(
            name='DitUniversityCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(blank=True, max_length=100, null=True)),
                ('CourseImage', models.ImageField(blank=True, null=True, upload_to='media/UniversityImage/')),
                ('CourseDepartment', models.CharField(blank=True, max_length=100, null=True)),
                ('CourseCapacity', models.IntegerField(blank=True, null=True)),
                ('CourseLink', models.CharField(blank=True, default='USMA/', max_length=500, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('university', models.ManyToManyField(max_length=200, to='USMAApp.universities')),
            ],
            options={
                'verbose_name_plural': 'DitUniversityCourses',
            },
        ),
    ]
