# Generated by Django 4.1.3 on 2023-08-06 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USMAApp', '0013_udsmuniversitycourses_udomuniversitycourses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dituniversitycourses',
            name='university',
        ),
        migrations.RemoveField(
            model_name='mustuniversitycourses',
            name='university',
        ),
        migrations.RemoveField(
            model_name='udomuniversitycourses',
            name='university',
        ),
        migrations.RemoveField(
            model_name='udsmuniversitycourses',
            name='university',
        ),
        migrations.AddField(
            model_name='dituniversitycourses',
            name='university',
            field=models.ForeignKey(default=0, max_length=200, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.universities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mustuniversitycourses',
            name='university',
            field=models.ForeignKey(default=0, max_length=200, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.universities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='udomuniversitycourses',
            name='university',
            field=models.ForeignKey(default=0, max_length=200, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.universities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='udsmuniversitycourses',
            name='university',
            field=models.ForeignKey(default=0, max_length=200, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.universities'),
            preserve_default=False,
        ),
    ]
