# Generated by Django 4.1.3 on 2023-08-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USMAApp', '0016_articles_articlelink_websitearticles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allprojects',
            name='PdfFile',
        ),
        migrations.RemoveField(
            model_name='allprojects',
            name='ProjectLink',
        ),
        migrations.RemoveField(
            model_name='allprojects',
            name='VideoLink',
        ),
        migrations.AlterField(
            model_name='allprojects',
            name='ProjectImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/ProjectImage/'),
        ),
        migrations.AlterField(
            model_name='allprojects',
            name='StudentEmail',
            field=models.EmailField(blank=True, default='youremail@gmail.com', max_length=100, null=True),
        ),
    ]
