# Generated by Django 4.1.3 on 2023-08-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USMAApp', '0018_remove_computermaintenanceexperts_categoryname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experts',
            name='ShortDescription',
        ),
        migrations.AlterField(
            model_name='experts',
            name='Phone',
            field=models.CharField(blank=True, default='+255', max_length=13, null=True),
        ),
    ]
