# Generated by Django 4.1.3 on 2023-08-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USMAApp', '0020_remove_articlescategory_shortdescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=200)),
                ('Message', models.TextField(blank=True, max_length=5000, null=True)),
                ('Phone', models.CharField(default='+255', max_length=13)),
                ('Email', models.EmailField(default='@gmail.com', max_length=254)),
                ('Place', models.CharField(max_length=200)),
                ('send_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ContactMe',
            },
        ),
    ]
