# Generated by Django 4.1.3 on 2023-08-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USMAApp', '0021_contactme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileapplicationsarticles',
            name='ArticlesName',
        ),
        migrations.RemoveField(
            model_name='websitearticles',
            name='ArticlesName',
        ),
        migrations.DeleteModel(
            name='AIArticles',
        ),
        migrations.DeleteModel(
            name='MobileApplicationsArticles',
        ),
        migrations.DeleteModel(
            name='WebsiteArticles',
        ),
    ]
